runtime: python39  # or newer
service: ar25  # name your GAE service
instance_class: F2  # or F1 for cheaper, lower performance

entrypoint: gunicorn -b :$PORT -w 2 -k gthread --threads 2 --timeout 30 main:app

handlers:
- url: /icons
  static_dir: static/icons
- url: /static
  static_dir: static
- url: /.*
  script: auto